#!/bin/sh
./check_dawnbringer.py $(git diff --cached --name-only --diff-filter=ACM | grep .png | grep -v yellow-star.png)
modified_py_files=$(git diff --cached --name-only --diff-filter=ACM | grep '.py$')
if [ -n "$modified_py_files" ]; then
    pylint $modified_py_files
fi
