name: build

on:
  push:
    branches:
    - '*'

jobs:
  build:
    name: Lint, test & build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install flask livereload pylint pytest -r requirements.txt
          git clone https://github.com/clintbellanger/heroine-dusk
      - name: Linter
        run: |
          pylint pdf_game/ gen_pdf.py hall_of_fame/hof_app.py trailer/*.py
      - name: Tests
        run: |
          pytest pdf_game/
      - name: Build PDF
        run: |
          NO_TQDM=1 PYTHONUNBUFFERED=1 ./gen_pdf.py
