name: build

on:  # cf. https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Lint, test & build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r extra-requirements.txt
          git clone https://github.com/clintbellanger/heroine-dusk
      - name: Linter
        run: pylint pdf_game/ gen_pdf.py hall_of_fame/hof_app.py trailer/*.py
      - name: Tests
        run: pytest pdf_game/ -vv --showlocals
      - name: Checking that all images use the DawnBringer palette
        run: ./check_dawnbringer.py $(git ls-files | grep .png | grep -v yellow-star.png)
      - name: Build PDF
        run: NO_TQDM=1 PYTHONUNBUFFERED=1 ./gen_pdf.py
      - name: Build trailer GIFs
        run: PYTHONPATH=. trailer/gen_promo_images.py
