name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build & release PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/clintbellanger/heroine-dusk
      - name: Build PDF
        run: |
          echo "__version__ = '$GITHUB_REF'" > pdf_game/__init__.py
          NO_TQDM=1 PYTHONUNBUFFERED=1 ./gen_pdf.py --no-marked-content
          zip/gen_zips.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: cf. [CHANGELOG.md](https://github.com/Lucas-C/undying-dusk/blob/main/CHANGELOG.md)
      - name: Upload PDF only ZIP
        id: upload-pdf-only-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./zip/undying-dusk-pdf-only.zip
          asset_name: undying-dusk-pdf-only.zip
          asset_content_type: application/zip
      - name: Upload Sumatra bundle ZIP
        id: upload-sumatra-bundle-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./zip/undying-dusk-with-sumatra-windows.zip
          asset_name: undying-dusk-with-sumatra-windows.zip
          asset_content_type: application/zip
      - name: Publish on itch.io
        run: ./publish-on-itch.io.sh ${{ github.ref }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
